# Generated by Django 5.0.2 on 2024-02-25 19:24

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(choices=[('TA', 'Танк'), ('HA', 'Хилер'), ('DD', 'Дэмэдж дилер'), ('TR', 'Трейдер'), ('GM', 'Гилдмастер'), ('QG', 'Квестгивер'), ('WA', 'Кузнецы'), ('TA', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний')], max_length=2, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_post', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('date_post', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMORPG.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(verbose_name='Текст')),
                ('date_comment', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('confirmation_comment', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMORPG.post', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
